angular
.module("trails",['ngRoute','trails.controllers','trails.services'])
.config(function($routeProvider){

		$routeProvider
		.when('/',{
			controller:'login-controller',
			templateUrl:'app/templates/view-login.html'
		})
		.when('/view-main',{
			controller:'main-controller',
			templateUrl:'app/templates/view-main.html',
			resolve:{
				"check":function($location){
					if(XMPP.isConnected){
						$location.path("/view-main");
					}
					else{
						$location.path("/");
					}
				}
			}
		})
		.when('/view-offers',{
			controller:'offers-controller',
			templateUrl:'app/templates/view-offers.html',
			resolve:{
				"check":function(access,$location){
					if(access.isAllowed()){
						$location.path("/view-offers");
					}
					else{
						$location.path("/");
					}
				}
			}
		})
		.otherwise({redirectTo:'/'});

	});